config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = @list.id
    @bookmark.save
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])

  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container pt-5">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "add new movie" %>
  <% end %>
  <%= link_to "back", list_path(@list), class: "btn btn-primary m-5" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All lists</h1>

<% @lists.each do |list| %>
  <%= link_to list_path(list), style: "text-decoration: none" do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, width: 400, crop: :fill %>')">
      <%= list.name %>
    </div>
  <% end  %>
<% end %>
<%= link_to "create a new List", new_list_path, class: "btn btn-primary m-5" %>

app/views/lists/new.html.erb
<div class="container pt-5" >
  <%= simple_form_for @list do |f| %>
    <p>enter your lists's name</p>
    <%= f.text_field :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "add new list" %>
  <% end %>
  <%= link_to "back", lists_path, class: "btn btn-primary m-5" %>
</div>

app/views/lists/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, width: 400, crop: :fill %>')">
  <%= @list.name %>
</div>
<p>This list contains <%= @list.movies.size %> movies</p>
<div class="container">
  <div class="wrapper">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card-movie">

        <img src="http://loremflickr.com/300/300/<%= bookmark.movie.title %>">
        <div class="card-trip-infos">
          <div>
            <h2><%= bookmark.movie.title %> </h2>
            <p><%= bookmark.movie.overview %></p>
          </div>
          <h2 class="card-trip-pricing">Raiting <%= bookmark.movie.rating %></h2>
        </div>
      </div>
    <% end %>
  </div>
<%= link_to "add a movie", new_list_bookmark_path(@list), class: "btn btn-primary" %>
<%= link_to "back", lists_path, class: "btn btn-primary m-5" %>
</div>